MODULE READIUIUC
  USE BASFUN
CONTAINS
!--------------------------------------------
!*** DETERMINES C, XI AND ZETA FROM X AND Z
!*** ALSO ZETATAIL, Z CAN BE LOWER OR UPPER
!*** IT DOESN'T MATTER
!--------------------------------------------
  SUBROUTINE ADIMENSIONALIZATION(N,X,Z,C,XI,ZETA,ZETATAIL)
    IMPLICIT REAL(8)(A-H,O-Z)
    REAL(8),DIMENSION(N)::X,Z,XI,ZETA
    XMAX=-1.0D30
    ZMAX=-1.0D30
    XMIN=+1.0D30
    ZMIN=+1.0D30
    IMAX=1
    DO I=1,N
      IF(X(I).GE.XMAX)THEN
        IMAX=I
        XMAX=X(I)
      END IF
      IF(ABS(X(I)).LE.1.0D-10)ZTAIL=Z(I)
      XMIN=MIN(XMIN,X(I))
      ZMAX=MAX(ZMAX,Z(I))
      ZMIN=MIN(ZMIN,Z(I))
    END DO
    C=XMAX-XMIN
    C1=1.0D00/C
    DO I=1,N
      XI(I)=C1*X(I)
      ZETA(I)=C1*Z(I)
    END DO
    ZETATAIL=C1*ZTAIL
  END SUBROUTINE ADIMENSIONALIZATION

!-----------------------------
!*** BERNSTEIN SHAPE FUNCTION
!-----------------------------
  REAL(8) FUNCTION SHAPEFUNCTION(I,NDEG,XI)
    IMPLICIT REAL(8)(A-H,O-Z)
    REAL(8)::XI
    INTEGER::I
    XI=MAX(0.0D00,XI)
    BERNSTEINPOL=FACTORIAL(NDEG)/(FACTORIAL(I)*FACTORIAL(NDEG-I))
    BERNSTEINPOL=BERNSTEINPOL*(XI**I)*(1.0D00-XI)**(NDEG-I)
    SHAPEFUNCTION=(XI**0.5D00)*(1.0D00-XI)*BERNSTEINPOL
  END FUNCTION SHAPEFUNCTION

!-----------------------
!*** INTERPOLATION WITH 
!-----------------------
  REAL(8) FUNCTION FINTERPOLATEFORREALCOORDINATES(XI,A,NDEG,ZET)
    IMPLICIT REAL(8)(A-H,O-Z)
    REAL(8),DIMENSION(NDEG+1)::A,SFL
    DO I=1,NDEG+1
      SFL(I)=SHAPEFUNCTION(I-1,NDEG,XI)
    ENDDO
    FINTERPOLATEFORREALCOORDINATES=DOTPROD(NDEG+1,A,SFL)+ZET*(1.0D00-XI)
  END FUNCTION FINTERPOLATEFORREALCOORDINATES

!--------------------------------------------
!*** DETERMINES THE INTERPOLATION PARAMETERS
!--------------------------------------------
  SUBROUTINE DETERMINESA(N,NDEG,XL,ZL,AL,ZETATAIL)
    IMPLICIT REAL(8)(A-H,O-Z)
    REAL(8),DIMENSION(N)::XL,ZL,XIL,ZETAL
    REAL(8)::CL,CU
    REAL(8),DIMENSION(N)::RHSL
    REAL(8),DIMENSION(N,NDEG+1)::LMATRIX
    REAL(8),DIMENSION(NDEG+1)::AL,ONE
    REAL(8),DIMENSION(NDEG+1,NDEG+1)::MATRIXONE,MATRIXONE1
!***********************************************************
    CALL ADIMENSIONALIZATION(N,XL,ZL,CL,XIL,ZETAL,ZETATAIL)
    DO I=1,NDEG+1
      DO J=1,N
        LMATRIX(J,I)=SHAPEFUNCTION(I-1,NDEG,XIL(J))
      END DO
    END DO
    DO J=1,N
      RHSL(J)=ZETAL(J)-XIL(J)*ZETATAIL
    END DO
    CALL MATVEC2(NDEG+1,N,LMATRIX,RHSL,ONE)
!*** MATRIX MULTIPLICATION
    MATRIXONE=0.0D00
    DO I=1,NDEG+1
      DO J=1,NDEG+1
        MATRIXONE(I,J)=0.0D00
        DO K=1,N
          MATRIXONE(I,J)=MATRIXONE(I,J)+LMATRIX(K,I)*LMATRIX(K,J)
        END DO
      END DO
    END DO
    CALL INVMAT(NDEG+1, DET, MATRIXONE, MATRIXONE1)
    CALL MATVEC(NDEG+1,NDEG+1,MATRIXONE1,ONE,AL)
  END SUBROUTINE DETERMINESA

  SUBROUTINE READUIUCPROF(NOMEFICHEIRO,IBOTTOM,XL,ZL,ITOP,XU,ZU,XINTERIOR)
    IMPLICIT REAL(8)(A-H,O-Z)
    CHARACTER(100)::STR
    REAL(8),DIMENSION(:),ALLOCATABLE::XL,ZL,XU,ZU
    REAL(8),DIMENSION(2)::XINTERIOR
    CHARACTER(*)::NOMEFICHEIRO
    IU=IUNIT()
    OPEN(IU,FILE=TRIM(ADJUSTL(NOMEFICHEIRO)),STATUS="UNKNOWN")
    READ(IU,"(A)",IOSTAT=KO)STR
    ITOP=0
    IBOTTOM=0
    XBEFORE=0.0d00
    DO
      READ(IU,*,IOSTAT=IO)XGASH,YGASH
      IF(ITOP.GT.2.AND.XGASH.GE.XBEFORE)EXIT
      IF(IO.NE.0)EXIT
      ITOP=ITOP+1
      XBEFORE=XGASH
    END DO
    IF(ITOP.LE.2)THEN
      WRITE(*,*) "WRONG ITOP"
      READ(*,*)
    END IF
    BACKSPACE(IU)
    DO
      READ(IU,*,IOSTAT=IO)XGASH,YGASH
      IF(IO.NE.0)EXIT
      IBOTTOM=IBOTTOM+1
    END DO
    IF(IBOTTOM.LE.2)THEN
      WRITE(*,*) "WRONG IBOTTOM"
      READ(*,*)
    END IF
    ALLOCATE(XL(IBOTTOM),ZL(IBOTTOM),XU(ITOP),ZU(ITOP))
    REWIND (IU)
    IPTOP=0
    IPBOT=0
    READ(IU,*)
    DO I=1,ITOP
      READ(IU,*)XU(I),ZU(I)
    END DO
    DO I=1,IBOTTOM
      READ(IU,*)XL(I),ZL(I)
    END DO
    RU=HUGE(1.0D00)
    RL=HUGE(1.0D00)
    DO I=1,ITOP
      IF(ABS(XU(I)-0.5D00).LE.RU)THEN
        RU=ABS(XU(I)-0.5D00)
        IPTOP=I
      END IF
    END DO
    DO I=1,IBOTTOM
      IF(ABS(XL(I)-0.5D00).LE.RL)THEN
        RL=ABS(XL(I)-0.5D00)
        IPBOT=I
      END IF
    END DO
    IF(IPBOT.NE.0.AND.IPTOP.NE.0)THEN
      XINTERIOR(1)=(XU(IPTOP)+XL(IPBOT))*0.5D00
      XINTERIOR(2)=(ZU(IPTOP)+ZL(IPBOT))*0.5D00
    ELSE
      WRITE(*,*)"IPBOT,IPTOP",ipbot,iptop
      READ(*,*)
    END IF
  END SUBROUTINE READUIUCPROF

  SUBROUTINE SETSAIRFOILCOORDINATES(IU,NX,NY,NPROF,NDEG,AL,ZETAL,AU,ZETAU,xinterior)
    IMPLICIT REAL(8)(A-H,O-Z)
    REAL(8),DIMENSION(NDEG+1)::AL,AU
    REAL(8),dimension(2)::xinterior
    REAL(8),DIMENSION(:,:),ALLOCATABLE::X
    INTEGER,DIMENSION(:,:),ALLOCATABLE::EDGES
    NNE=2*NX+2*NY
    NNI=2*(NPROF+1)
    NN=NNE+NNI
    ALLOCATE(X(2,NN))
    NEE=NNE
    NEI=NNI
    NE=NEE+NEI
    ALLOCATE(EDGES(2,NE))
    XMIN=-6.0D00
    XMAX=+6.0D00
    ZMIN=-4.0D00
    ZMAX=+4.0D00
    DO I=0,NX
      X(1,I+1)=XMAX*(1.0D00-I/(1.0D00*NX))+XMIN*I/(1.0D00*NX)
      X(2,I+1)=ZMAX
      EDGES(1,I+1)=I+1
      EDGES(2,I+1)=I+2
    ENDDO
    DO I=1,NY
      X(1,NX+1+I)=XMIN
      X(2,NX+1+I)=ZMAX*(1.0D00-1.0D00*I/(1.0D00*NY))+ZMIN*I/(1.0D00*NY)
      EDGES(1,NX+I+1)=NX+I+1
      EDGES(2,NX+I+1)=NX+I+2
    ENDDO
    DO I=1,NX
      X(1,NX+NY+1+I)=XMIN*(1.0D00-1.0D00*I/(1.0D00*NX))+XMAX*I/(1.0D00*NX)
      X(2,NX+NY+1+I)=ZMIN
      EDGES(1,NX+NY+1+I)=NX+NY+I+1
      EDGES(2,NX+NY+1+I)=NX+NY+I+2
    ENDDO
    DO I=1,NY-1
      X(1,NX+NY+NX+1+I)=XMAX
      X(2,NX+NY+NX+1+I)=ZMIN*(1.0D00-1.0D00*I/(1.0D00*NY))+ZMAX*I/(1.0D00*NY)
      EDGES(1,NX+NY+NX+1+I)=NX+NY+NX+1+I
      EDGES(2,NX+NY+NX+1+I)=NX+NY+NX+2+I
    ENDDO
    EDGES(2,NX+NY+NX+NY)=1
    !! NOW THE AIRFOIL
    DO I=0,NPROF
        XI=(1.0D00*I)/(1.0D00*NPROF)
        X(1,2*NX+2*NY+1+I)=XI
        X(2,2*NX+2*NY+1+I)=FINTERPOLATEFORREALCOORDINATES(XI,AL,NDEG,ZETAL)-1.0D-3
        EDGES(1,2*NX+2*NY+1+I)=2*NX+2*NY+1+I
        EDGES(2,2*NX+2*NY+1+I)=2*NX+2*NY+2+I
    ENDDO
    DO I=0,NPROF
      XI=1.0D00-(1.0D00*I)/(1.0D00*NPROF)
      X(1,2*NX+2*NY+2+NPROF+I)=XI
      X(2,2*NX+2*NY+2+NPROF+I)=FINTERPOLATEFORREALCOORDINATES(XI,AU,NDEG,ZETAU)+1.0D-3
      EDGES(1,2*NX+2*NY+2+NPROF+I)=2*NX+2*NY+2+NPROF+I
      EDGES(2,2*NX+2*NY+2+NPROF+I)=2*NX+2*NY+3+NPROF+I
    ENDDO
    EDGES(2,2*NX+2*NY+2+2*NPROF)=2*NX+2*NY+1
    WRITE(IU,"(12I8)")NN,2,0,1
    DO I=1,NNE
      WRITE(IU,"(I8,2E15.6,I8)")I,X(1,I),X(2,I),1
    ENDDO
    DO I=NNE+1,NN
      WRITE(IU,"(I8,2E15.6,I8)")I,X(1,I),X(2,I),2
    ENDDO
    WRITE(IU,"(12I8)")NE,1
    DO I=1,NEE
      WRITE(IU,"(12I8)")I,EDGES(1,I),EDGES(2,I),1
    END DO
    DO I=NEE+1,NE
      WRITE(IU,"(12I8)")I,EDGES(1,I),EDGES(2,I),2
    ENDDO
    WRITE(IU,"(12I8)")1
    WRITE(IU,"(I8,2E15.6)")1,xinterior
  END SUBROUTINE SETSAIRFOILCOORDINATES

  
  SUBROUTINE SETSAIRFOIL(IU,NX,NY,NPROF,NDEG,AL,ZETAL,AU,ZETAU,xinterior)
    IMPLICIT REAL(8)(A-H,O-Z)
    REAL(8),DIMENSION(NDEG+1)::AL,AU
    REAL(8),DIMENSION(2)::XINTERIOR
    REAL(8),DIMENSION(:,:),ALLOCATABLE::X
    WRITE(IU,"(a)")"CUSTOM AREIAS"
    NNI=2*(NPROF+1)
    ALLOCATE(X(2,NNI))
    DO I=0,NPROF
      XI=1.0D00-(1.0D00*I)/(1.0D00*NPROF)
      X(1,1+I)=XI
      X(2,1+I)=FINTERPOLATEFORREALCOORDINATES(XI,AU,NDEG,ZETAU)
    ENDDO
    DO I=0,NPROF
      XI=(1.0D00*I)/(1.0D00*NPROF)
      X(1,NPROF+2+I)=XI
      X(2,NPROF+2+I)=FINTERPOLATEFORREALCOORDINATES(XI,AL,NDEG,ZETAL)
    ENDDO
    DO I=1,NPROF+1
      WRITE(IU,"(2E15.6,I8)")X(1,I),X(2,I)
    ENDDO
    DO I=NPROF+2,(NPROF+1)*2
      WRITE(IU,"(2E15.6,I8)")X(1,I),X(2,I)
    ENDDO
  END SUBROUTINE SETSAIRFOIL
END MODULE READIUIUC

!-----------------------------
!***
!-----------------------------
PROGRAM WRITEAIRFOILDAT
  USE READIUIUC
  USE BASFUN
  IMPLICIT REAL(8)(A-H,O-Z)
  INTEGER,PARAMETER::NDEG=3
  REAL(8),DIMENSION(2)::xinterior
  REAL(8),DIMENSION(:),ALLOCATABLE::XL,ZL,XU,ZU
  REAL(8),DIMENSION(NDEG+1)::AL,AU
  INTEGER::mode=1
  LOGICAL::FE
  xinterior(1)=0.3d00
  xinterior(2)=0.0d00
  INQUIRE(FILE="parametersopt.txt", EXIST=FE)
  IF(.NOT.FE)THEN
    WRITE(*,*)"PARAMETERSOPT NOT FOUND"
    STOP
  END IF
  kup=iunit()
  OPEN(kup,file="parametersopt.txt",status="unknown")
  READ(kup,*)al(1:ndeg+1),zetal,au(1:ndeg+1),zetau  
  CLOSE(kup)
  OPEN(IU,FILE="parametersopt.dat",status="unknown")
  nprof=181
  CALL SETSAIRFOIL(IU,NX,NY,NPROF,NDEG,AL,ZETAL,AU,ZETAU,XINTERIOR)
  CLOSE(iu)
END PROGRAM 
